DF <- read.table("household_power_consumption.txt",sep=";",header=TRUE)
DF[,1]<-as.Date(DF$Date,"%d/%m/%Y")
DF2<-subset(DF,DF[,1]=="2007-02-01")
DF3<-subset(DF,DF[,1]=="2007-02-02")
DF<-rbind(DF2,DF3)
plot(ts(as.numeric(DF$Sub_metering_1)-2),xaxt='n',yaxt='n',xlab="",ylab="Energy sub metering",ylim=range(0,DF$Sub_metering_2,DF$Sub_metering_1,DF$Sub_metering_3))
axis(side=1,labels=c("Thu","Fri","Sat"),at=c(0,nrow(DF)/2,nrow(DF)))
axis(side=2,labels=c(0,10,20,30),at=c(0,10,20,30))
lines(ts(as.numeric(DF$Sub_metering_2)-2),col="red")
lines(ts(as.numeric(DF$Sub_metering_3)),col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=2,lty=1)
dev.copy(png,file="plot3.png",width=480,height=480)
dev.off()